<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<NoWarn>$(NoWarn);NU1902</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Infrastructure\Repositories\EmailNewsLetterRepo\**" />
		<Compile Remove="Models\Currency\**" />
		<Compile Remove="Repositories\**" />

		<Content Remove="Infrastructure\Repositories\EmailNewsLetterRepo\**" />
		<Content Remove="Models\Currency\**" />
		<Content Remove="Repositories\**" />

		<EmbeddedResource Remove="Infrastructure\Repositories\EmailNewsLetterRepo\**" />
		<EmbeddedResource Remove="Models\Currency\**" />
		<EmbeddedResource Remove="Repositories\**" />

		<None Remove="Infrastructure\Repositories\EmailNewsLetterRepo\**" />
		<None Remove="Models\Currency\**" />
		<None Remove="Repositories\**" />
	</ItemGroup>

	<ItemGroup>
		<Compile Remove="Controllers\CmsController.cs" />
		<Compile Remove="Application\Services\CMS\DTOs\ArticleRawDto.cs" />
	</ItemGroup>

	<!-- Main dependencies -->
	<ItemGroup>
		<PackageReference Include="Azure.Data.Tables" Version="12.11.0" />
		<PackageReference Include="Azure.Search.Documents" Version="12.0.0" />
		<PackageReference Include="Azure.Storage.Queues" Version="12.25.0" />

		<!-- FIXED Azure SDK alignment -->
		<PackageReference Include="Azure.Core" Version="1.54.0" />
		<PackageReference Include="Azure.Identity" Version="1.21.0" />
		<PackageReference Include="Azure.Monitor.Query" Version="1.7.1" />

		<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="3.1.0" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.7" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		  <PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.8" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.8">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Stripe.net" Version="51.1.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SharedLib\SharedLib.csproj" />
		<ProjectReference Include="..\ZucchiniCore\ZucchiniCore.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Infrastructure\Repositories\SearchRepo\" />
	</ItemGroup>

</Project>