name: Build and deploy ASP.Net Core app to Azure Web App - ZucchiniNews

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.x"

      - name: Clean
        run: dotnet clean ZucchiniMVC/Zucchinimvc.csproj -c Release

      - name: Restore
        run: dotnet restore ZucchiniMVC/Zucchinimvc.csproj

      - name: Publish
        run: dotnet publish ZucchiniMVC/Zucchinimvc.csproj -c Release -o ./publish /p:UseAppHost=false

      - name: Check runtime files
        run: ls ./publish/*.runtimeconfig.json

      - name: Zip package
        run: |
          cd publish
          zip -r ../app.zip .

      - uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app

      - uses: azure/webapps-deploy@v3
        with:
          app-name: "ZucchiniNews"
          slot-name: "Production"
          package: ./app.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A33A3476DBE24AB49CEC801EF8B13566 }}